// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity ^0.8.0;

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "./interfaces/IMerkleDistributor.sol";
import "./libraries/MerkleProof.sol";

/// @notice use for claim reward
contract MerkleDistributor is IMerkleDistributor {
    address public immutable override token;
    bytes32 public override merkleRoot;

    event SettleFlashLoan(
        bytes32 indexed merkleRoot,
        uint256 indexed index,
        uint256 amount,
        uint256 settleBlockNumber
    );

    struct MerkleDistributor {
        bytes32 merkleRoot;
        uint256 index;
        uint256 amount;
        uint256 settleBlockNumber;
    }
    MerkleDistributor[] public merkleDistributors;

    // This is a packed array of booleans.
    mapping(uint256 => uint256) private claimedBitMap;
    address public owner;

    modifier onlyOwner() {
        require(msg.sender == owner, "not authorized!");
        _;
    }

    constructor(address token_) {
        token = token_;
        owner = msg.sender;
    }

    /// @param _index  the token will be distributed to users;
    /// @param _amount  the token will be distributed to users;
    /// @param _settleBlockNumber  the token will be distributed to users;
    /// @param _merkleRoot the merkle root generated by all user reward info
    function distributeReward(
        uint256 _index,
        uint256 _amount,
        uint256 _settleBlockNumber,
        bytes32 _merkleRoot
    ) external onlyOwner {
        merkleRoot = _merkleRoot;
        require(_index == merkleDistributors.length, "index already exists");

        uint256 currAmount = IERC20(token).balanceOf(address(this));
        require(currAmount >= _amount, "Insufficient reward funds");

        require(block.number >= _settleBlockNumber, "!blockNumber");

        if (merkleDistributors.length > 0) {
            MerkleDistributor memory md = merkleDistributors[
                merkleDistributors.length - 1
            ];
            require(
                md.settleBlockNumber < _settleBlockNumber,
                "!settleBlockNumber"
            );
        }

        merkleDistributors.push(
            MerkleDistributor(_merkleRoot, _index, _amount, _settleBlockNumber)
        );

        emit SettleFlashLoan(_merkleRoot, _index, _amount, _settleBlockNumber);
    }

    /// @notice check user whether claimed
    /// @param index check user index  in reward list or not
    function isClaimed(uint256 index) public view override returns (bool) {
        uint256 claimedWordIndex = index / 256;
        uint256 claimedBitIndex = index % 256;
        uint256 claimedWord = claimedBitMap[claimedWordIndex];
        uint256 mask = (1 << claimedBitIndex);
        return claimedWord & mask == mask;
    }

    function _setClaimed(uint256 index) private {
        uint256 claimedWordIndex = index / 256;
        uint256 claimedBitIndex = index % 256;
        claimedBitMap[claimedWordIndex] =
            claimedBitMap[claimedWordIndex] |
            (1 << claimedBitIndex);
    }

    /// @notice  user  claimed  reward with proof
    /// @param index user index in reward list
    /// @param account user address
    /// @param amount  user reward amount
    /// @param merkleProof  user merkelProof ,generate by merkel.js
    function claim(
        uint256 index,
        address account,
        uint256 amount,
        bytes32[] calldata merkleProof
    ) external override {
        require(!isClaimed(index), "MerkleDistributor: Drop already claimed.");

        // Verify the merkle proof.
        bytes32 node = keccak256(abi.encodePacked(index, account, amount));
        require(
            MerkleProof.verify(merkleProof, merkleRoot, node),
            "MerkleDistributor: Invalid proof."
        );

        // Mark it claimed and send the token.
        _setClaimed(index);
        require(
            IERC20(token).transfer(account, amount),
            "MerkleDistributor: Transfer failed."
        );

        emit Claimed(index, account, amount);
    }

    /// @notice  owner withdraw the rest token
    function claimRestTokens(address to) public returns (bool) {
        // only owner
        require(msg.sender == owner);
        require(IERC20(token).balanceOf(address(this)) >= 0);
        require(
            IERC20(token).transfer(to, IERC20(token).balanceOf(address(this)))
        );
        return true;
    }
}
