/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockToken from "./mockToken";
export * as officialTokens from "./officialTokens";
export { WorldCupToken__factory } from "./WorldCupToken__factory";
