/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WorldCup } from "./WorldCup";
export * as factories from "./factories";
export { WorldCup__factory } from "./factories/WorldCup__factory";
