/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as baycErc721Sol from "./BAYC-ERC721.sol";
export type { baycErc721Sol };
import type * as bitDaoErc20Sol from "./BitDao-ERC20.sol";
export type { bitDaoErc20Sol };
