/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokens from "./tokens";
export type { tokens };
export type { Lock } from "./Lock";
export type { WorldCup } from "./WorldCup";
