/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { WorldCupV1__factory } from "./WorldCupV1__factory";
export { WorldCupV2__factory } from "./WorldCupV2__factory";
