/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockToken from "./mockToken";
export type { mockToken };
import type * as officialTokens from "./officialTokens";
export type { officialTokens };
export type { WorldCupToken } from "./WorldCupToken";
